In [29]:
import numpy as np
A=([1,2,3],[4,5,6],[7,8,9])
B=([5,5,4],[2,3,9],[1,1,1])
C=np.dot(A,B)
print(C)

[[ 12  14  25]
 [ 36  41  67]
 [ 60  68 109]]


In [30]:
D=np.array([[1,2],[5,6]])
E=np.array([[11],[12]])
F=D.dot(E)

In [31]:
G=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(G[0][1])
print(G[1][2])

2
6


In [32]:
H=np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in H:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [33]:
for num in H.flat:
    print(num)

1
2
3
4
5
6
7
8
9


In [37]:
np.arange(10,51,10).reshape(5,1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [41]:
S=np.arange(12).reshape(3,4)
print(S)
for num in np.nditer(S,order='C'):
    print(num)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [42]:
for num in np.nditer(S,order='F'):
    print(num)

0
4
8
1
5
9
2
6
10
3
7
11


In [43]:
for x in np.nditer(S,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
