In [29]:
import numpy as np
A=([1,2,3],[4,5,6],[7,8,9])
B=([5,5,4],[2,3,9],[1,1,1])
C=np.dot(A,B)
print(C)

[[ 12  14  25]
 [ 36  41  67]
 [ 60  68 109]]


In [30]:
D=np.array([[1,2],[5,6]])
E=np.array([[11],[12]])
F=D.dot(E)

In [31]:
G=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(G[0][1])
print(G[1][2])

2
6


In [32]:
H=np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in H:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [33]:
for num in H.flat:
    print(num)

1
2
3
4
5
6
7
8
9


In [37]:
np.arange(10,51,10).reshape(5,1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [41]:
S=np.arange(12).reshape(3,4)
print(S)
for num in np.nditer(S,order='C'):
    print(num)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [42]:
for num in np.nditer(S,order='F'):
    print(num)

0
4
8
1
5
9
2
6
10
3
7
11


In [46]:
for x in np.nditer(S,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [48]:
for x in np.nditer(S,op_flags=['readwrite']):
    x[...]=x*x

In [49]:
S

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [54]:
X=np.arange(1,13,1).reshape(3,4)
Y=np.arange(21,33,1).reshape(3,4)
print(X)
print(Y)
for x,y in np.nditer([X,Y]):
    print(x,y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
1 21
2 22
3 23
4 24
5 25
6 26
7 27
8 28
9 29
10 30
11 31
12 32


In [56]:
K=np.array([[1,2,3],[4,5,6],[7,8,9]])
K[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
K[0,:]

array([1, 2, 3])

In [58]:
Z=np.array([[1,2,3],[4,5,6],[7,8,9]])
W=np.array([[5,6,7],[8,9,10],[10,11,12]])
np.vstack((Z,W))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [59]:
np.hstack((Z,W))

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10],
       [ 7,  8,  9, 10, 11, 12]])